version: '3.7'
services:
#  djangoapp:
#    build:
#      dockerfile: Dockerfile.djangoapp
#  radius-server:
#    build:
#      dockerfile: Dockerfile.radius
#    ports:
#      - "1812:1812"
#      - "1813:1813"
  postgres:
    image: kartoza/postgis:13.0
    restart: always
    volumes:
      - "./data:/var/lib/postgresql/data"
    expose:
      - 5432
    env_file:
      - .env_postgres
