# Generated by Django 4.1.2 on 2022-10-29 18:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='level_access_network',
            fields=[
                ('id_level_access_network', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_level_access', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='level_access_network_devices',
            fields=[
                ('id_level_access_network_devices', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_level_access', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='nas',
            fields=[
                ('id_nas', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('short_name', models.TextField(max_length=30)),
                ('secret_key', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='nas_port_type',
            fields=[
                ('id_nas_port_type', models.BigAutoField(primary_key=True, serialize=False)),
                ('port_type', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user_groups',
            fields=[
                ('id_user_group', models.BigAutoField(primary_key=True, serialize=False)),
                ('group', models.TextField(max_length=40)),
                ('id_level_access_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.level_access_network')),
                ('id_level_access_network_devices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.level_access_network_devices')),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id_users', models.BigAutoField(primary_key=True, serialize=False)),
                ('usurname', models.TextField(max_length=40)),
                ('uname', models.TextField(max_length=20, null=True)),
                ('ulast_name', models.TextField(max_length=30, null=True)),
                ('mac_address_eth', models.TextField(max_length=17, validators=[django.core.validators.RegexValidator(message='Unknown type mac address', regex='/^[0-9a-f]{2}(:[0-9a-f]{2}){5}$/i')])),
                ('mac_address_wifi', models.TextField(max_length=17, validators=[django.core.validators.RegexValidator(message='Unknown type mac address', regex='/^[0-9a-f]{2}(:[0-9a-f]{2}){5}$/i')])),
                ('mac_address_adapt', models.TextField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Unknown type mac address', regex='/^[0-9a-f]{2}(:[0-9a-f]{2}){5}$/i')])),
                ('date_create', models.DateTimeField()),
                ('id_level_access_network_devices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.level_access_network_devices')),
                ('id_user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.user_groups')),
                ('level_access_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.level_access_network')),
            ],
        ),
        migrations.CreateModel(
            name='fail_tries',
            fields=[
                ('id_fail_try', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_nas_connect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.nas')),
                ('id_nas_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to='website.nas_port_type')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.nas_port_type')),
            ],
        ),
        migrations.CreateModel(
            name='accounting',
            fields=[
                ('id_acct', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip_access', models.GenericIPAddressField()),
                ('acct_start_time', models.DateTimeField()),
                ('acct_update_time', models.DateTimeField()),
                ('acct_stop_time', models.DateTimeField()),
                ('connect_info_start', models.DateTimeField()),
                ('connect_info_stop', models.DateTimeField()),
                ('id_nas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.nas')),
                ('id_nas_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to='website.nas_port_type')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.users')),
            ],
        ),
    ]
