# Generated by Django 4.1.2 on 2022-11-01 12:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mac_addresses',
            fields=[
                ('id_user_mac', models.BigAutoField(default=0, primary_key=True, serialize=False)),
                ('mac_address_eth', models.TextField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Неизвестный тип мак адреса', regex='^[a-fA-F0-9]{2}(:[a-fA-F0-9]{2}){5}$')], verbose_name='Мак адрес сетевой карты ethernet')),
                ('mac_address_wifi', models.TextField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Неизвестный тип мак адреса', regex='^[a-fA-F0-9]{2}(:[a-fA-F0-9]{2}){5}$')], verbose_name='Мак адрес сетевой карты WiFi')),
                ('mac_address_adapt', models.TextField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Неизвестный тип мак адреса', regex='^[a-fA-F0-9]{2}(:[a-fA-F0-9]{2}){5}$')], verbose_name='Мак адрес сетевого адаптера')),
            ],
            options={
                'verbose_name': 'Таблица мак адресов пользователей',
                'verbose_name_plural': 'Таблица мак адресов пользователей',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='id_mac',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.mac_addresses', verbose_name='Мак адреса'),
        ),
    ]
