# Generated by Django 4.1.2 on 2022-10-29 19:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='usurname',
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='user@mail.com', max_length=254, verbose_name='Электронный адрес'),
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.TextField(max_length=40, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='acct_start_time',
            field=models.DateTimeField(verbose_name='Начало учёта'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='acct_stop_time',
            field=models.DateTimeField(verbose_name='Конец учёта'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='acct_update_time',
            field=models.DateTimeField(verbose_name=' Обновление учёта'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='connect_info_start',
            field=models.DateTimeField(verbose_name='Начало соединения'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='connect_info_stop',
            field=models.DateTimeField(verbose_name='Конец соединения'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='id_nas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.nas', verbose_name='NAS'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='id_nas_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to='website.nas_port_type', verbose_name='Тип доступа'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.users', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='ip_access',
            field=models.GenericIPAddressField(verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='fail_tries',
            name='id_nas_connect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.nas', verbose_name='На каком NAS произошла ошибка'),
        ),
        migrations.AlterField(
            model_name='fail_tries',
            name='id_nas_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to='website.nas_port_type', verbose_name='Тип доступа'),
        ),
        migrations.AlterField(
            model_name='level_access_network',
            name='type_level_access',
            field=models.TextField(max_length=20, verbose_name='Тип разрешения доступа к сети'),
        ),
        migrations.AlterField(
            model_name='level_access_network_devices',
            name='type_level_access',
            field=models.TextField(max_length=20, verbose_name='Тип разрешения доступа к сетевому оборудованию'),
        ),
        migrations.AlterField(
            model_name='nas',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='nas',
            name='secret_key',
            field=models.TextField(max_length=30, verbose_name='Секретный ключ'),
        ),
        migrations.AlterField(
            model_name='nas',
            name='short_name',
            field=models.TextField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='nas_port_type',
            name='port_type',
            field=models.TextField(max_length=20, verbose_name='Тип порта NAS'),
        ),
        migrations.AlterField(
            model_name='user_groups',
            name='group',
            field=models.TextField(max_length=40, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='user_groups',
            name='id_level_access_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.level_access_network', verbose_name='Тип разрешения доступа к сети'),
        ),
        migrations.AlterField(
            model_name='user_groups',
            name='id_level_access_network_devices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.level_access_network_devices', verbose_name='Тип разрешения доступа к сетевому оборудованию'),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_create',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='id_level_access_network_devices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.level_access_network_devices', verbose_name='Тип разрешения доступа к сетевому оборудованию'),
        ),
        migrations.AlterField(
            model_name='users',
            name='id_user_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.user_groups', verbose_name='Группа пользователя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='level_access_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.level_access_network', verbose_name='Тип разрешения доступа к сети'),
        ),
        migrations.AlterField(
            model_name='users',
            name='mac_address_adapt',
            field=models.TextField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Unknown type mac address', regex='/^[0-9a-f]{2}(:[0-9a-f]{2}){5}$/i')], verbose_name='Мак адрес сетевого адаптера'),
        ),
        migrations.AlterField(
            model_name='users',
            name='mac_address_eth',
            field=models.TextField(max_length=17, validators=[django.core.validators.RegexValidator(message='Unknown type mac address', regex='/^[0-9a-f]{2}(:[0-9a-f]{2}){5}$/i')], verbose_name='Мак адрес сетевой карты ethernet'),
        ),
        migrations.AlterField(
            model_name='users',
            name='mac_address_wifi',
            field=models.TextField(max_length=17, validators=[django.core.validators.RegexValidator(message='Unknown type mac address', regex='/^[0-9a-f]{2}(:[0-9a-f]{2}){5}$/i')], verbose_name='Мак адрес сетевой карты WiFi'),
        ),
        migrations.AlterField(
            model_name='users',
            name='ulast_name',
            field=models.TextField(blank=True, max_length=30, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='users',
            name='uname',
            field=models.TextField(blank=True, max_length=20, null=True, verbose_name='Имя'),
        ),
    ]
