# Generated by Django 4.1.2 on 2022-11-01 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_mac_addresses_users_id_mac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mac_addresses',
            name='mac_address_adapt',
        ),
        migrations.AddField(
            model_name='mac_addresses',
            name='mac_address_add_1',
            field=models.TextField(help_text='Дополнительный мак адрес (Необязательно)', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Неизвестный тип мак адреса', regex='^[a-fA-F0-9]{2}(:[a-fA-F0-9]{2}){5}$')], verbose_name='Мак адрес сетевого адаптера'),
        ),
        migrations.AddField(
            model_name='mac_addresses',
            name='mac_address_add_2',
            field=models.TextField(help_text='Дополнительный мак адрес (Необязательно)', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Неизвестный тип мак адреса', regex='^[a-fA-F0-9]{2}(:[a-fA-F0-9]{2}){5}$')], verbose_name='Мак адрес сетевого адаптера'),
        ),
    ]
