# Generated by Django 4.1.2 on 2022-10-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_users_usurname_users_email_users_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='level_access_network_devices',
            name='attribute',
            field=models.TextField(default='Mikrotik-Group', max_length=25, verbose_name='Аттрибут'),
        ),
    ]
