# Generated by Django 4.1.2 on 2022-11-02 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_mac_addresses_mac_address_add_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounting',
            old_name='id_user',
            new_name='id_user_name',
        ),
        migrations.RemoveField(
            model_name='accounting',
            name='acct_start_time',
        ),
        migrations.RemoveField(
            model_name='accounting',
            name='acct_stop_time',
        ),
        migrations.RemoveField(
            model_name='accounting',
            name='acct_update_time',
        ),
        migrations.RemoveField(
            model_name='accounting',
            name='connect_info_start',
        ),
        migrations.RemoveField(
            model_name='accounting',
            name='connect_info_stop',
        ),
        migrations.RemoveField(
            model_name='accounting',
            name='id_nas',
        ),
        migrations.RemoveField(
            model_name='accounting',
            name='id_nas_port',
        ),
        migrations.RemoveField(
            model_name='accounting',
            name='ip_access',
        ),
        migrations.AddField(
            model_name='accounting',
            name='acct_authentic',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Аутентификатор'),
        ),
        migrations.AddField(
            model_name='accounting',
            name='acct_delay_time',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Время ожидания'),
        ),
        migrations.AddField(
            model_name='accounting',
            name='acct_session_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Идентификатор сессии'),
        ),
        migrations.AddField(
            model_name='accounting',
            name='acct_status_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Статус учёта'),
        ),
        migrations.AddField(
            model_name='accounting',
            name='called_station_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Аутентифицируемый сервис'),
        ),
        migrations.AddField(
            model_name='accounting',
            name='calling_station_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Аутентифицируемая станция'),
        ),
        migrations.AddField(
            model_name='accounting',
            name='dateinfo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время запроса'),
        ),
        migrations.AddField(
            model_name='accounting',
            name='id_nas_identifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.nas'),
        ),
        migrations.AddField(
            model_name='accounting',
            name='id_nas_port_type',
            field=models.ForeignKey(blank=True, max_length=25, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.nas_port_type', verbose_name='Тип порта'),
        ),
        migrations.AddField(
            model_name='accounting',
            name='service_type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Тип сервиса'),
        ),
    ]
