# Generated by Django 4.1.2 on 2022-10-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_accounting_options_alter_fail_tries_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='network_login',
            field=models.TextField(default='', help_text='Логин для подключения к сетевому оборудованию (Необязательно)', max_length=30, verbose_name='Логин для подключения к сетевому оборудованию'),
        ),
        migrations.AddField(
            model_name='users',
            name='network_password',
            field=models.TextField(default='', help_text='Пароль для подключения к сетевому оборудованию (Необязательно)', max_length=30, verbose_name='Пароль для подключения к сетевому оборудованию '),
        ),
    ]
