# Generated by Django 4.1.2 on 2022-11-02 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_id_user_accounting_id_user_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='accounting',
        ),
    ]
