# Generated by Django 4.0.6 on 2022-07-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nasname', models.TextField(db_index=True)),
                ('shortname', models.TextField()),
                ('type', models.TextField(default='Mikrotik')),
                ('ports', models.IntegerField()),
                ('secret', models.TextField()),
                ('server', models.TextField()),
                ('community', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='nasreload',
            fields=[
                ('NASIPAddress', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('ReloadTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='radacct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AcctSessionId', models.TextField()),
                ('AcctUniqueID', models.TextField(unique=True)),
                ('UserName', models.TextField()),
                ('GroupName', models.TextField()),
                ('Realms', models.TextField()),
                ('NASIPAddress', models.GenericIPAddressField()),
                ('NASPortId', models.TextField()),
                ('NASPortType', models.TextField()),
                ('AcctStartTime', models.DateTimeField()),
                ('AcctUpdateTime', models.DateTimeField()),
                ('AcctStopTime', models.DateTimeField()),
                ('AcctInterval', models.BigIntegerField()),
                ('AcctSessionTime', models.BigIntegerField()),
                ('AcctAuthentic', models.TextField()),
                ('ConnectInfoStart', models.TextField()),
                ('ConnectInfoStop', models.TextField()),
                ('AcctInputOctets', models.BigIntegerField()),
                ('AcctOutputOctets', models.BigIntegerField()),
                ('CalledStationId', models.TextField()),
                ('CallingStationId', models.TextField()),
                ('AcctTerminateCause', models.TextField()),
                ('ServiceType', models.TextField()),
                ('FramedProtocol', models.TextField()),
                ('FramedIPAddress', models.GenericIPAddressField()),
                ('FramedIPv6Address', models.GenericIPAddressField()),
                ('FramedIPv6Prefix', models.GenericIPAddressField()),
                ('FramedInterfaceId', models.TextField()),
                ('DelegatedIPv6Prefix', models.TextField()),
                ('Class', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='radcheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.TextField(default='')),
                ('Attribute', models.TextField(default='')),
                ('op', models.CharField(default='==', max_length=2)),
                ('Value', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='radgroupcheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupName', models.TextField(default='')),
                ('Attribute', models.TextField(default='')),
                ('op', models.CharField(default='==', max_length=2)),
                ('Value', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='radgroupreply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupName', models.TextField(default='')),
                ('Attribute', models.TextField(default='')),
                ('op', models.CharField(default='==', max_length=2)),
                ('Value', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='radpostauth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('reply', models.TextField()),
                ('CalledStationId', models.TextField()),
                ('CallingStationId', models.TextField()),
                ('authdate', models.DateTimeField(default='now()')),
                ('Class', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='radreply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.TextField(default='')),
                ('Attribute', models.TextField(default='')),
                ('op', models.CharField(default='==', max_length=2)),
                ('Value', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='radusergroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.TextField(db_index=True, default='')),
                ('GroupName', models.TextField(default='')),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
    ]
