# Generated by Django 4.0.6 on 2022-07-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radius', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radcheck',
            name='op',
            field=models.CharField(choices=[('==', '=='), ('+=', '+='), (':=', ':='), ('!=', '!='), ('>', '>'), ('>=', '>='), ('<=', '<='), ('<', '<'), ('=~', '=~'), ('!~', '!~'), ('=*', '=*'), ('!*', '!*')], default='==', max_length=2),
        ),
        migrations.AlterField(
            model_name='radgroupcheck',
            name='op',
            field=models.CharField(choices=[('==', '=='), ('+=', '+='), (':=', ':='), ('!=', '!='), ('>', '>'), ('>=', '>='), ('<=', '<='), ('<', '<'), ('=~', '=~'), ('!~', '!~'), ('=*', '=*'), ('!*', '!*')], default='==', max_length=2),
        ),
        migrations.AlterField(
            model_name='radgroupreply',
            name='op',
            field=models.CharField(choices=[('==', '=='), ('+=', '+='), (':=', ':='), ('!=', '!='), ('>', '>'), ('>=', '>='), ('<=', '<='), ('<', '<'), ('=~', '=~'), ('!~', '!~'), ('=*', '=*'), ('!*', '!*')], default='==', max_length=2),
        ),
        migrations.AlterField(
            model_name='radreply',
            name='op',
            field=models.CharField(choices=[('==', '=='), ('+=', '+='), (':=', ':='), ('!=', '!='), ('>', '>'), ('>=', '>='), ('<=', '<='), ('<', '<'), ('=~', '=~'), ('!~', '!~'), ('=*', '=*'), ('!*', '!*')], default='==', max_length=2),
        ),
    ]
