# Generated by Django 4.0.6 on 2022-07-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radius', '0002_alter_radcheck_op_alter_radgroupcheck_op_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nas',
            name='type',
            field=models.TextField(choices=[('0', 'Other'), ('1', 'Mikrotik'), ('2', 'Cisco')], default='Other'),
        ),
    ]
